apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: PaymentManagement
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - springboot
    - microservice
  links:
    - url: http://localhost:9901/PaymentManagement/
      title: PaymentManagement Website
      icon: dashboard
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
  providesApis:
    - PaymentManagement
  #consumesApis:
  #  - petstore
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: PaymentManagement
  description: ${{ values.description }}
spec:
  type: openapi
  lifecycle: experimental
  owner: ${{values.destination.owner}}
  definition:
    $text: https://github.com/${{values.destination.owner + "/" + values.destination.repo}}/blob/master/PaymentManagement/src/main/resources/api-docs.yaml
